### ISSUE TITLE
Error on regular setup with Packer

### ISSUE THREAD

**Issue by collinpeters** [IndianBoy42/tree-sitter-just#1]
Not sure if this is a Packer issue... or something with my config.

I have `use 'IndianBoy42/tree-sitter-just'` in my packer config. If I think do a `require('tree-sitter-just').setup()` I get the following error:
```
E5113: Error while calling lua chunk: vim.lua:63: ...ker/start/tree-sitter-just/lua/tree-sitter-just/init.lua:1: '=' expected near 'M'
```

If I do the manual setup it works fine.

**Comment by IndianBoy42** [comment]
Ah, a little typo, i guess i used the manual setup as well so i missed it
