### ISSUE TITLE
No syntax highlighting?

### ISSUE THREAD

**Issue by nyonson** [IndianBoy42/tree-sitter-just#11]
I am not sure if the plugin is loading correctly for me. I went the "manual" install path and its listed under `TSInstallInfo`. When I open a `justfile` though, the highlighting looks the same. I noticed the the filetype is still `conf`, do I have to do some more configuring for it to recognize justfiles?

**Comment by nyonson** [comment]
Was able to get things working by installing as a plugin. Also needed the `{}` brackets.

**Comment by liiil825** [comment]
```
{
  'nathom/filetype.nvim',
  lazy = false,
  opts = {
    overrides = {
      literal = {
        justfile = 'just',
      },
    },
  },
},
```
Install the filetype.nvim plugin to make justfile execute just syntax

note: (lazy = false) sets no lazy loading. I couldn't find a suitable event to load, so I had to cancel it.

**Comment by tgross35** [comment]
Seems like this is resolved. Feel free to submit a PR to the readme if something could be more clear there!
