### ISSUE TITLE
Update Helix with the latest queries

### ISSUE THREAD

**Issue by tgross35** [IndianBoy42/tree-sitter-just#126]
This grammar has gotten quite a bit better and Helix can probably update. The change for this just means bumping the checkout version and updating the queries - the queries in `queries-src/` should be what is needed.

It would be great to have some Helix people review those queries too. If they have any changes, please let me know so we can get them upstream.

**Comment by woojiq** [comment]
I actually wanted to do this about a month ago, but then I noticed it was crashing, so I put the task on hold. I would like to update queries in the helix repository, but when the injection detection gets better. Does it detect "bash" now as it did in 5766e756ff5bfe9caddeb8c5fe369558f5dc5092..e4e24050c061faf7a767310b9dfc391d576d2df1 which were reverted?

**Comment by tgross35** [comment]
Hey, thanks for the interest! It currently detects the recipe language via shebangs but does not have a fallback. This is partially because precedence is kind of in a confusing state now - nvim and zed use last-wins, TS [just changed to also use last-wins](https://github.com/tree-sitter/tree-sitter/releases/tag/v0.21.0), and helix is hopefully changing pretty soon  https://github.com/helix-editor/helix/issues/9436.

But it is easy enough to add, I will do that soon.

**Comment by tgross35** [comment]
@woojiq I actually went ahead and got this started https://github.com/helix-editor/helix/pull/9850, figured that's probably easiest for the first time since I can make any changes needed here quicker.

**Comment by tgross35** [comment]
My PR was superseded, the update is complete!
