### ISSUE TITLE
Missing argument `arg` to setup function in documentation

### ISSUE THREAD

**Issue by alealv** [IndianBoy42/tree-sitter-just#13]
Setup function requires an `arg` argument which looks for `local` key. But the README suggested to run only `require("tree-sitter-just").setup()`

I guess it needs local path, right?

```
E5108: Error executing lua ...ker/start/tree-sitter-just/lua/tree-sitter-just/init.lua:24: attempt to index local 'arg' (a nil value)
stack traceback:
        ...ker/start/tree-sitter-just/lua/tree-sitter-just/init.lua:24: in function 'setup'
        [string ":lua"]:1: in main chunk
```

**Comment by jess-sol** [comment]
Was able to get it to work by adding an empty map as the arg:
```
require("tree-sitter-just").setup({})
```

**Comment by alealv** [comment]
It doesn't work for me. And it makes sense that it doesn't because it's trying to access the key without checking

```
			url = arg["local"] and join_paths(
```

**Comment by jess-sol** [comment]
The rest of that line has a default value if `arg["local"]` is missing:
```
url = arg["local"] and join_paths(
  vim.fn.stdpath("data"),
  "site",
  "pack",
  "packer",
  "start",
  "tree-sitter-just"
) or "https://github.com/IndianBoy42/tree-sitter-just", -- local path or git repo
```

This is the install_info value I see when calling `setup({})`:
```
{
  install_info = {
    branch = "main",
    files = { "src/parser.c", "src/scanner.cc" },
    url = "https://github.com/IndianBoy42/tree-sitter-just"
  },
  maintainers = { "@IndianBoy42" },
  <metatable> = {
    __newindex = <function 1>
  }
}
```

**Comment by tgross35** [comment]
Thanks @jess-sol for helping out!

I am hoping this is no longer a problem so going to close, lease feel free to reopen if not.

A documentation PR would be accepted if this information is generally useful.
