### ISSUE TITLE
Add the `just` grammar to Zed

### ISSUE THREAD

**Issue by tgross35** [IndianBoy42/tree-sitter-just#138]
Zed also uses tree-sitter grammars, but no Just at this time: https://github.com/zed-industries/zed/tree/a6dbaac6538c1648de1943f071d006d5acb5a5bc/crates/languages/src

Wouldn't hurt to add.

**Comment by 21CSM** [comment]
Seems like it fixed by: zed-industries/extensions#478

**Comment by tgross35** [comment]
Yes, thanks for the update!
