### ISSUE TITLE
Support slashes in recipe name

### ISSUE THREAD

**Issue by Jasha10** [IndianBoy42/tree-sitter-just#156]
Hello,

Thank you for your work on tree-sitter-just!

Currently, `just` supports slashes in recipe names:
```just
# justfile
foo/bar:
  echo baz
```
However, the above seems to break tree-sitter-just, and syntax highlighting fails.

**Comment by tgross35** [comment]
That sounds easy enough, I didn’t know they were allowed. Any chance you can find a specific list of allowed characters in Just’s documentation?

**Comment by Jasha10** [comment]
I found https://github.com/casey/just/blob/master/GRAMMAR.md, which does not explicitly mention that slashes are allowed. According to [section 1.8.4 in the just manual](https://just.systems/man/en/chapter_66.html), the GRAMMAR.md file is "non-normative."

**Comment by tgross35** [comment]
Thank you for taking a look into this!
