### ISSUE TITLE
Installation instructions at nvim-treesitter just point here

### ISSUE THREAD

**Issue by AddictArts** [IndianBoy42/tree-sitter-just#157]
Just is not available in a TSInstall and the installation instructions are circular, this points to nvim-treesitter, and nvim-treesitter pints to here. Sorry, I am new to this and can't make sense of the installation instructions. I had used Lazy to load this and once on a justfile I could TSInstall just. However, it seems like now it is implied I don't need to use this a plugin and nvim-treesitter has it, but that is not with Neovim 0.9.5.

**Comment by tgross35** [comment]
Which version of nvim-treesitter are you on? It was only added very recently.

**Comment by drskoolie** [comment]
@AddictArts I had the same issue, but I went to my plugin manager and updated Treesitter.

After that, I was able to do `:TSInstall just`

**Comment by tgross35** [comment]
I am going to close this under the assumption that it is just a version mismatch. Feel free to reopen @AddictArts if you try @drskoolie's suggestion and still have issues.

**Comment by AddictArts** [comment]
@drskoolie Thanks, indeed this did the trick.

Any tips though on getting the filetype right instead of having to do `:set filetype=just` on a `justfile`?

@tgross35 Thanks

**Comment by tgross35** [comment]
https://github.com/IndianBoy42/tree-sitter-just/blob/6c2f018ab1d90946c0ce029bb2f7d57f56895dff/ftdetect/just.vim is what we use in the repo, but that should happen automatically via nvim-treesitter. If it is doing something like working for `foo.just` but not `justfile`, it might be worth opening an issue there.
