### ISSUE TITLE
Not working with .justfile in neovim

### ISSUE THREAD

**Issue by andradei** [IndianBoy42/tree-sitter-just#163]
Neovim 0.9.5

Installed via `:TSInstall just`

Renaming to `justfile` didn't work either.

Manually running `:set filetype=just` makes tree-sitter identify the file but there is no highlighting, although "go to definition" seems to work.

![image](https://github.com/IndianBoy42/tree-sitter-just/assets/2653546/9a6509b1-dab3-4474-a3e0-9447cfb9b6ba)

**Comment by tgross35** [comment]
Can you specify your nvim treesitter version? And are you using the version from the repo, or the version available with nvim treesitter?

**Comment by andradei** [comment]
Tree-sitter version is `master` (see screenshot below).
I've installed via `:TSInstall just`, not from the repo (as a Lazy.nvim plugin in my case)
![image](https://github.com/IndianBoy42/tree-sitter-just/assets/2653546/cbf80d13-52f5-4f65-8b50-dd25f440c54d)

**Comment by andradei** [comment]
Since neovim 0.10 was release this week and a bunch of plugins upgraded with it (and I am waiting for the Arch package). There is a chance nvim-treesitter is using some new API nvim 0.9.5 doesn't have.

**Comment by andradei** [comment]
After finally upgrading to neovim 0.10 and getting the latest tree-sitter version, everything is working again.

**Comment by tgross35** [comment]
Great, thank you for confirming!
