### ISSUE TITLE
Shebangs not working unless they have a forward slash

### ISSUE THREAD

**Issue by sid-6581** [IndianBoy42/tree-sitter-just#175]
I installed with nvim-treesitter, and this is the result in the kitchen sink example from the just repo:

![image](https://github.com/user-attachments/assets/d9ffb22a-558e-4163-b70e-27257bccac60)

The syntax highlighting is wrong until the next `/`. The relevant portion of the tree:

![image](https://github.com/user-attachments/assets/ef5d8df7-1f1d-455b-8368-e8c2bc619dbf)

**Comment by leon-barrett** [comment]
I also encountered this issue, and I attempted to resolve it in PR https://github.com/IndianBoy42/tree-sitter-just/pull/179 . I welcome feedback and improvements.

**Comment by tgross35** [comment]
This should be fixed by https://github.com/IndianBoy42/tree-sitter-just/pull/179.
