### ISSUE TITLE
Support rule groups

### ISSUE THREAD

**Issue by lvignoli** [IndianBoy42/tree-sitter-just#176]
Currently, [rule groups](https://github.com/IndianBoy42/tree-sitter-just) are not supported and even produce a parse error, — breaking any highlighting based on it.

Example:

```just
[group('python')]
fmt:
    ruff format || true
```

![Capture d’écran 2024-09-17 à 16 55 28](https://github.com/user-attachments/assets/8bc59f99-1bb5-4c29-832d-46886d164f52)

This is the output from Zed's AST using [jackTabsCode/zed-just](https://github.com/jackTabsCode/zed-just) which leverages tree-sitter-just.

(An example from the tree-sitter playground would have been more informative, but I cannot compile tree-sitter-just locally, I'll try again but platform specific issue it seems.)

**Comment by kennyp** [comment]
Looks like this is fixed by #183 as well.
