### ISSUE TITLE
Automatic indenting not working as expected (Helix Macos)

### ISSUE THREAD

**Issue by machinemob** [IndianBoy42/tree-sitter-just#189]
Not sure if this is a user(me)-ignorance issue: Entering a task name and colon and typing enter, I expect the next line to be automatically indented with subsequent lines following that indent. Note that this functionality works as expected for makefile.

Expected...

```
mytask:<enter>
    indent should start here
    subsequent lines should automatically match the above indent
    ...and so on
```
   
What I get.....

```
mytask:<enter>
no indent
no indent
```

What I get if I manually indent the line after the task...

```
mytask:<enter>
<tab>indent starts here as expected
              following line should match the above indent but is further indented
              subsequent lines match the above indent
              ...and so on
```

Details:
**Helix:** helix 24.7 (079f5442) (Homebrew)
**OS:**  MacOS Sonoma 14.4.1 (23E224)
**hx --health output:**
        Configured language servers: None
        Configured debug adapter: None
        Configured formatter: None
        Highlight queries: ✓
        Textobject queries: ✓
        Indent queries: ✓
**Helix languages.toml:** Nothing added as docs say just functionality is already included(?)

Thanks for reading.

**Comment by tgross35** [comment]
@machinemob I just noticed this issue was opened and closed on the same day. Did you find a resolution?
