### ISSUE TITLE
no support for attributes?

### ISSUE THREAD

**Issue by swarnimarun** [IndianBoy42/tree-sitter-just#19]
## Issue:
There seems to be no support for attributes.

```justfile
[unix]
foo:
    cat /tmp/logs.txt

[windows]
foo:
    Get-Content $env:TEMP/logs.txt
```

**Aside:** In case I am misunderstanding something let me know, if no one is working on it will pick this up myself in a couple weeks(or once I have a bit more free time).

## Notes:

If anyone else wants to pick this up it would be added to recipes themselves I believe, and you can change the grammar to parse something like,

```js
{
attributes: ($) => repeat($.attribute),
attribute: ($) =>
      seq(
        "[",
        $.attribute_keys,
        "]"
      ),
attribute_keys: ($) => choice("private", "unix", "macos", "windows", "linux", "no-exit-message", "no-cd"),
}
```

and add attributes as optional parameter to recipe,

```js
    recipe: ($) => seq(optional($.attributes), $.recipeheader, $.NEWLINE, optional($.body)),
```

I believe there might be some parsing issue with the above, and as I have forgotten some specifies of tree-sitter grammars so take above only as a starting point, and research from below.

https://github.com/IndianBoy42/tree-sitter-just/blob/4e5f5f3ff37b12a1bbf664eb3966b3019e924594/grammar.js#L135

**Comment by IndianBoy42** [comment]
I wrote this parser before the attribute syntax existed. I'd definitely appreciate any help with implementing it. I probably won't have the time or motivation anytime soon.

**Comment by tgross35** [comment]
Parsing should work with #35, I'll add keyword highlighting later
