### ISSUE TITLE
[Feature request] support for shebang `#/usr/bin/env just --justfile` at top of file

### ISSUE THREAD

**Issue by Jasha10** [IndianBoy42/tree-sitter-just#20]
Hello, thank you for sharing your work on justfile syntax!

The `just` docs and readme mention that adding a shebang `#!/usr/bin/env just --justfile` works wll at the top of executable `justfile`s.

I've noticed that sometimes `tree-sitter-just` does not interact well with a shebang at the top of the justfile -- the syntax highlighting can go wrong once I add the shebang. Is this because this package treats shebangs specially?

Here is an minimal example of a justfile for which the highlighting is off (when viewed in Neovim with this package enabled):
```just
#!/usr/bin/env just --justfile

export BLA := "humbug"

foo:
  BAR="abc"
```

**Comment by tgross35** [comment]
Added in  #40, thanks!
