### ISSUE TITLE
Collaborators

### ISSUE THREAD

**Issue by IndianBoy42** [IndianBoy42/tree-sitter-just#28]
I've been absolutely swamped with schoolwork and kind of didn't expect this little project, that frankly is not well written and doesn't work very well, to attract so much attention. 

If anyone is interested making this a proper project then, either you can create a fork and I will link it and archive this repository. Or I can just add you as a collaborator

**Comment by tgross35** [comment]
I see you added me. Are you ok with me reviewing and merging some of the PRs?

**Comment by IndianBoy42** [comment]
Yeah, I saw you opened a PR which is what spurred me to make this

**Comment by tgross35** [comment]
Thanks, I'll see what I can do

**Comment by tgross35** [comment]
I'll close this out since I think the grammar is now in a better state, and I am happy to keep maintaining as needed.

**Comment by tgross35** [comment]
@IndianBoy42 could you enable auto merge on this repo? You just need to add a required status check for all four jobs, as I wrote up here: https://github.com/orgs/community/discussions/50327#discussioncomment-9693518

The four jobs:

![image](https://github.com/user-attachments/assets/f004fc61-a04d-407b-84d2-d03b1714b4f7)
